### ISSUE TITLE
"New Bounding box" tool writes segmentation polygons in incorrect format for COCO JSON

### ISSUE THREAD

**Issue by tcysin** [OvidijusParsiunas/myvision#17]
Noticed this when `pycocotools` started complaining.

[Data format](https://cocodataset.org/#format-data) page for COCO (section 1 - Object Detection) mentions that for detection tasks, `segmentation` field in annotation object must be either `RLE` or `[polygon]`:
```
"segmentation": RLE or [polygon],
```

Looks like a `polygon` itself is a **list** of vertices (however, i could not find any specification on that).

If we take a look at the annotated picture and its `json` annotation file, we see that segmentation field for annotation with `id=0` (made with *Bounding box* tool) is a list of floats, but for annotation with `id=1` (made with *Polygon* tool) is a list of lists.

![from-myvision](https://user-images.githubusercontent.com/24791800/116066180-71391580-a690-11eb-86b2-0e61ea9221d0.jpg)
![json-pic](https://user-images.githubusercontent.com/24791800/116066184-71d1ac00-a690-11eb-8e9f-63d91748d5aa.jpg)

Here is the zip with `json` file - the result of COCO JSON import.
[annotations.zip](https://github.com/OvidijusParsiunas/myvision/files/6376177/annotations.zip)

Could you check this out?

**Comment by OvidijusParsiunas** [comment]
Hey @tcysin, the bounding box segmentation result format does appear to be incorrect, I'm going to fix this right now!

**Comment by OvidijusParsiunas** [comment]
The issue should now be fixed. Once again thankyou @tcysin  for raising it and if you have any other issues/requests/suggestions ti improve the application - you can always open a new issue :) Thankyou!
