### ISSUE TITLE
question: how to create my own classnames without the default classes?

### ISSUE THREAD

**Issue by eisneim** [OvidijusParsiunas/myvision#35]
when i export, i got unwanted classes like: dog, cat etc. how to mannually set my own classes ?

**Comment by OvidijusParsiunas** [comment]
Hi @eisneim, could you elaborate on the problem that you are observing.
If you want to create you own class names, all you need to do is to type in the name of the class that you want inside the 'Label Name' after you have drawn a shape, and then click 'Submit'. The exported file should use your custom class names.
If that is not the solution to your problem, I would be more than happy to assist you if you give me more details :)
